-- Sample data for Cafe Audit System demo (run after schema.sql)
USE restaurant_v2;

INSERT INTO categories (name) VALUES
  ('Hot Drinks'),
  ('Cold Drinks'),
  ('Food'),
  ('Desserts');

INSERT INTO suppliers (name, contact_info, email) VALUES
  ('Ethio Coffee Suppliers', '+251-911-000001', 'orders@ethiocoffee.et'),
  ('Fresh Dairy Co.', '+251-911-000002', 'sales@freshdairy.et'),
  ('Bakery Wholesale', '+251-911-000003', 'wholesale@bakery.et');

INSERT INTO inventory (name, unit, current_qty, min_threshold, unit_cost, sup_id) VALUES
  ('Arabica Coffee Beans', 'kg', 25.00, 5.00, 850.00, 1),
  ('Whole Milk', 'liter', 40.00, 10.00, 45.00, 2),
  ('Sugar', 'kg', 15.00, 3.00, 55.00, 1),
  ('Paper Cups (12oz)', 'unit', 500.00, 100.00, 2.50, 1),
  ('Croissant Dough', 'unit', 80.00, 20.00, 18.00, 3),
  ('Chocolate Syrup', 'liter', 8.00, 2.00, 220.00, 1),
  ('Ice Cubes', 'kg', 30.00, 5.00, 5.00, 2);

INSERT INTO products (name, description, price, cat_id) VALUES
  ('Espresso', 'Single shot of rich Arabica espresso', 35.00, 1),
  ('Cappuccino', 'Espresso with steamed milk and foam', 45.00, 1),
  ('Latte', 'Espresso with extra steamed milk', 50.00, 1),
  ('Iced Latte', 'Chilled latte over ice', 55.00, 2),
  ('Hot Chocolate', 'Rich chocolate with steamed milk', 48.00, 1),
  ('Croissant', 'Buttery baked croissant', 40.00, 3),
  ('Mocha', 'Espresso, chocolate, and steamed milk', 52.00, 1);

INSERT INTO recipes (product_id, item_id, qty_needed) VALUES
  (1, 1, 0.018), (1, 3, 0.005),
  (2, 1, 0.018), (2, 2, 0.150), (2, 3, 0.008), (2, 4, 1.000),
  (3, 1, 0.018), (3, 2, 0.250), (3, 3, 0.010), (3, 4, 1.000),
  (4, 1, 0.018), (4, 2, 0.200), (4, 3, 0.008), (4, 4, 1.000), (4, 7, 0.100),
  (5, 2, 0.200), (5, 6, 0.030), (5, 3, 0.010), (5, 4, 1.000),
  (6, 5, 1.000),
  (7, 1, 0.018), (7, 2, 0.180), (7, 6, 0.025), (7, 3, 0.008), (7, 4, 1.000);

-- Demo tables with QR tokens (tokens regenerated by install.php if needed)
INSERT INTO restaurant_tables (table_number, qr_token, status, capacity) VALUES
  ('T01', 'qr_t01_a8f3c2d1e9b4', 'available', 2),
  ('T02', 'qr_t02_b7e2d1c0f8a3', 'available', 4),
  ('T03', 'qr_t03_c6d1e0b9a7f2', 'available', 4),
  ('T04', 'qr_t04_d5c0f9b8e6a1', 'available', 6),
  ('T05', 'qr_t05_e4b9a8c7d5f0', 'available', 2),
  ('T06', 'qr_t06_f3a8b7c6e4d9', 'available', 4),
  ('T07', 'qr_t07_a2b7c6d5e3f8', 'available', 8),
  ('T08', 'qr_t08_b1c6d5e4f2a7', 'available', 4);
